### ISSUE TITLE
[연구소_박민욱] SQL Editor 결과 메뉴 중 실행계획 선택 시 행 걸리는 현상

### ISSUE THREAD

**Issue by orapmw** [sinsiway/data-studio-alpha#10]
SQL Editor 결과 메뉴 중 실행계획 선택 시 행 걸리는 현상
![image](https://user-images.githubusercontent.com/24932968/97400070-cbe7f380-1931-11eb-8668-43df2412ac57.png)

**Comment by sinsiway** [comment]
스크롤 라이브러리 제거 관련 문제로 인해 생긴 오류. 수정 완료
