### ISSUE TITLE
[마케팅_박병민] 기능 수정 요청 : 데이터 그리드 사용자에 의한 조절 필요

### ISSUE THREAD

**Issue by rowan420** [sinsiway/data-studio-alpha#12]
![image](https://user-images.githubusercontent.com/73562781/97510658-904c3880-19c8-11eb-984a-8c46f5633439.png)

- 데이터 그리드 컬럼 조절시 좌/우 조절 기능 필요
- 데이터 그리드 상단 조절시 하단에 그리드가 채워 지는 것이 아니라 여백 발생

위 기능은 기존 타 솔루션들과 같이 사용자가 유동적으로 조절할 수 있도록 하는 기능 필요

**Comment by sinsiway** [comment]
@rowan420 
요청하신 그리드 헤더의 컬럼 사이즈 조절 기능 및 상하단 그리드의 유동적인 여백 조절 기능 추가하였습니다.
