### ISSUE TITLE
[마케팅_박병민] SQL 실행 오류 : SQL 실행 실패 및 행 걸리는 현상

### ISSUE THREAD

**Issue by rowan420** [sinsiway/data-studio-alpha#15]
![image](https://user-images.githubusercontent.com/73562781/97532902-a4a92900-19fa-11eb-9580-4a4c2770c5c4.png)

- select * from crm 실행시 실행되지 않고 행걸리는 현상
- 새로운 에디터창에서는 정상적으로 실행

**Comment by sinsiway** [comment]
오류 수정 완료
