### ISSUE TITLE
[R&D_고진아] 로그인된 상태에서 URL 복사 후 새 브라우저에서 해당 URL로 접속 시 로딩 페이지에서 진행 멈춤

### ISSUE THREAD

**Issue by jako-sinsiway** [sinsiway/data-studio-alpha#16]
● 문제 상황
로그인 완료된 상황에서 URL을 복사한 후 접속 정보가 없는 브라우저에서 해당 URL을 사용해 사이트에 접속하는 경우 로딩 페이지에서 멈춤

● 문제 상황 시나리오
① A 브라우저에서 로그인
② A 브라우저 주소창 URL 복사
③ B 브라우저 주소창에 복사한 URL 넣은 후 접속
④ 로딩 화면이 뜨고 기다려도 다음 화면이 뜨지 않음

● 문제 상황 화면
![image](https://user-images.githubusercontent.com/72972980/97953828-04ca1180-1de5-11eb-82c1-a804066140f8.png)

● 기대 결과
해당 URL 사용 불가 메시지 출력 혹은 로그인 화면으로 이동

**Comment by sinsiway** [comment]
설명 그대로 테스트시 동일한 결과를 얻을 수 없음.
더 자세한 시나리오가 필요함.

**Comment by poorants** [comment]
@jako-sinsiway 
해당 이슈는 이기종 브라우저 간에서 발생할 수 있는 문제로 
로그인 페이지인 petra/init.do 를 제외한 url 경로로 강제 접속할 때 
기존 로그인 정보를 찾을 수 없을때 행이 걸리는 현상으로 분석 됩니다. 

이는 이기종 브라우저 간 local storage 경로가 다른데서 발생하는 문제로 
로그인 페이지를 제외 한 타 페이지로 접속 시 lccal storage에 로그인 정보가 없을 때 
로그인 페이지로 자동 이동하도록 수정 예정입니다.

**Comment by sinsiway** [comment]
@jako-sinsiway 위 답변과 내용 동일하게 수정하였습니다.
