### ISSUE TITLE
[R&D_고진아] DB 접속 결과 확인 불가

### ISSUE THREAD

**Issue by jako-sinsiway** [sinsiway/data-studio-alpha#17]
● 문제 상황
접근 가능한 DBMS 목록에 DBMS 등록 후 접속 시도 시 문제가 있는 경우 결과 확인 불 

● 문제 상황 시나리오
① 접근 가능한 DBMS 등록(* SOHA DB로 IP 대역이 10번대임)
![image](https://user-images.githubusercontent.com/72972980/97955398-6ee4b580-1de9-11eb-83c7-a40ad76010cd.png)

② 등록한 DBMS 접속 시도
③ 화면 변화 없음(* 개발자 도구에서는 504 에러 확인 가능)

● 문제 상황 화면
![Petra-Data-Studio_-DBMS-접속-결과-확인-불가](https://user-images.githubusercontent.com/72972980/97955951-ccc5cd00-1dea-11eb-9d9d-a431295254cc.gif)

● 기대 결과
접속 결과 메시지 출력 혹은 SQL 편집 화면으로 이동

**Comment by sinsiway** [comment]
DBMS 등록 화면에서 PING 테스트 및 접속 테스트 기능이 있습니다.
등록전 해당 기능들을 사용하여 접속이 되는지 확인 하시고 진행하시면 될것 같습니다.
그리고 생성 후 접속 눌러도 안된다면 타임아웃이 후 접속이 불가 하다는 메시지가 뜨도록 되있습니다.
