### ISSUE TITLE
[마케팅_박병민]  SQL 실행 오류 : 다중 쿼리 SELECT 실행시 실행 결과 미출력

### ISSUE THREAD

**Issue by rowan420** [sinsiway/data-studio-alpha#19]
![image](https://user-images.githubusercontent.com/73562781/98111989-c74cad80-1ee4-11eb-8d5f-20c87f57500b.png)

위와 같이 쿼리 실행히 일반적으로
2개의 그리드가 생성되어 2가지의 결과값을 보여 주거나
최종 쿼리에 대한 결과값이 출력 되는데

현재는 아무런 결과값도 출력 되지 않아 정상적으로 쿼리가 수행 되었는지 확인 불가

**Comment by sinsiway** [comment]
수정 완료
