### ISSUE TITLE
[마케팅_박병민] SQL 실행 오류 : 대량 데이터에 대한 쿼리 수행 불가

### ISSUE THREAD

**Issue by rowan420** [sinsiway/data-studio-alpha#20]
![image](https://user-images.githubusercontent.com/73562781/98112558-c2d4c480-1ee5-11eb-8e06-2fa8817f1146.png)

![image](https://user-images.githubusercontent.com/73562781/98112737-f6175380-1ee5-11eb-92b4-47f70386b095.png)

5365618 건의 데이터를 삭제 하였으나, 삭제 되지 않고 "504 Gateway Time-out" 발생

**Comment by poorants** [comment]
@rowan420 Gateway Time-out 시간을 1시간으로 수정했습니다.

이슈를 종료합니다.
