### ISSUE TITLE
[R&D_강창봉] 2개 이상의 동일한 DB 탭 접속 후, DB탭 일부 닫기 시, 나머지 탭에서도 연결이 종료되는 현상

### ISSUE THREAD

**Issue by sinsiway-cbkang** [sinsiway/data-studio-alpha#21]
SOHA DB에서 2개 이상의 동일한 DB 탭을 활성화 후, 한개의 탭을 닫기 시, 기존 나머지 탭에서도 연결이 종료되는 현상이 발생함

![img_gif_20_11_05_01](https://user-images.githubusercontent.com/67679085/98202348-2bb74d80-1f75-11eb-8abe-ad88d900bb60.gif)

**Comment by sinsiway** [comment]
수정 완료
