### ISSUE TITLE
[R&D_류대석] soha DB세션에서 실행 계획 시 멈춤

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#22]
# soha DB세션에서 실행 계획 시 멈춤
## 케이스 시나리오
1. soha에 접속합니다.
2. select 문 하나를 실행합니다.
3. 하단 "결과" 우측 "실행계획" 탭을 선택합니다.
4. 프로그레스 이미지가 무한 반복됩니다. 
5. 개발자도구 콘솔에서 확인되는 에러 메시지
```
Uncaught TypeError: Cannot read property 'DB_TYPE' of null
```

**Comment by sinsiway** [comment]
@sinsiwaysign soha에는 실행 계획 기능이 없기 때문에 해당 탭을 제거하여 보여주는 것으로 수정하였습니다.
