### ISSUE TITLE
[R&D_류대석] 접근 가능한 DB 추가 시 Alias 글자 수 제한에 공백 포함됨

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#23]
## 접근 가능한 DB 추가 시 Alias 글자 수 제한에 공백 포함됨
![image](https://user-images.githubusercontent.com/68979630/98765708-17b29680-2422-11eb-89fe-6292015bf7a6.png)
최소 5글자 이상 입력해야 하는 조건을 스페이스 입력으로 통과할 수 있음

**Comment by sinsiway** [comment]
alias에 trim으로 앞,뒤 여백 제거하여 벨리데이션 하도록 수정하였습니다.
