### ISSUE TITLE
[R&D_류대석] 처리 불가 세션 이슈

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#24]
#### 케이스 시나리오
1. 로그인 인증 유효시간 만료로 인해 로그아웃 된 화면에서 재 로그인
2. 기존 사용 중이던 탭(오라클 세션)을 닫으려고 하니 트랜젝션이 남아 있다는 알림 제공 > [닫기]로 탭 유지
3. 해당 탭에서 에디터 화면에 남아있던 SQL(select * from tab) 실행 시, 실행 실패, 반복 실행하여도 실패
![image](https://user-images.githubusercontent.com/68979630/99015469-6a15c380-2598-11eb-8255-25966d7f9bfa.png)
4. 브라우저 새로 고침 후 실행하여도 실패
5. 실행계획을 클릭하니 개발자도구에서 400 에러 확인
![image](https://user-images.githubusercontent.com/68979630/99015631-cd075a80-2598-11eb-95a0-9cb935aa745e.png)
6. 탭을 닫고 재접속하면 해결
#### 의견
1. 버그라면 수정
2. 해결하기 어려운 문제라면 사용자가 탭을 닫고 새로 열도록 유도하는 메시지 전달 했으면
수고하세요!

**Comment by sinsiway** [comment]
버그임이 확인되었고, 수정완료 하였습니다.
