### ISSUE TITLE
[R&D_류대석] 좌측 객체트리 감추기 요청

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#31]
###좌측 객체트리 감추기 요청
SQL에디터 화면을 좀 더 넓게 사용할 수 있도록 좌측 객체 트리의 열기/닫기 기능이 있었으면 함
![image](https://user-images.githubusercontent.com/68979630/100035323-3d3b9900-2e41-11eb-978a-523caf29eca2.png)

**Comment by sinsiway** [comment]
에디터 좌측 상단 첫번째 아이콘이 객체 파트 열기/숨김 기능입니다.
