### ISSUE TITLE
[R&D_류대석] 화면 DB접속 탭이 하나로 연결되어 보이는 현상

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#32]
### 화면 DB접속 탭이 하나로 연결되어 보이는 현상
####케이스 시나리오
1. DB접속 탭을 두개 이상 연다.
2. 첫 탭에서 테이블 Not Found 수행 실패 쿼리를 실행한다.
3. 첫 탭의 메시지 하단에 두번째 탭 화면이 붙어 나온다.
--
![image](https://user-images.githubusercontent.com/68979630/100037380-56464900-2e45-11eb-96d9-ec323adc3915.png)
--
![image](https://user-images.githubusercontent.com/68979630/100037986-86421c00-2e46-11eb-8763-a3fa5e0bd76b.png)
--
![image](https://user-images.githubusercontent.com/68979630/100037540-ade4b480-2e45-11eb-857f-e8d96926413a.png)

**Comment by sinsiway** [comment]
다중탭에서 그리드 엘리먼트가 없을 시 나는 오류.
수정 완료.

**Comment by sinsiway** [comment]
@sinsiwaysign 
다중탭에서 그리드 엘리먼트가 없을 시 나는 오류.
수정 완료.
