### ISSUE TITLE
[연구소_김동훈] 결과창 아이콘 구분바 추가 요청. 

### ISSUE THREAD

**Issue by poorants** [sinsiway/data-studio-alpha#33]
### AS-IS
![image](https://user-images.githubusercontent.com/65228542/100829625-25998b80-34a5-11eb-8339-61dedef002b4.png)

---
### TO-BE
![image](https://user-images.githubusercontent.com/65228542/100829680-4d88ef00-34a5-11eb-9366-8e2442200ce8.png)

## 요청사유
- 결과창 아이콘 중 다음 아이콘들은 데이터 에디트 모드일 때 트랜젝션 제어 부분으로 다른 아이콘과 구분선을 통해 분리하는게 직관성 있어보임
![image](https://user-images.githubusercontent.com/65228542/100829789-8b861300-34a5-11eb-9ba0-f2c2f17fd1d8.png)

**Comment by sinsiway** [comment]
@kimdhe88 반영 완료 하였습니다.
![image](https://user-images.githubusercontent.com/65210145/102184624-17ab2800-3ef3-11eb-8364-a489a63277b7.png)
