### ISSUE TITLE
[연구소_박종한]mongodb 객체검색기 안보이는 현상

### ISSUE THREAD

**Issue by jhparkk** [sinsiway/data-studio-alpha#37]
![datastudio](https://user-images.githubusercontent.com/41284486/101739917-8e1ee300-3b0b-11eb-87f3-1a8097aaeaec.png)

상용 클라이언트 - NoSQLBooster for MongoDB

![NoSQLBooster1](https://user-images.githubusercontent.com/41284486/101739981-9f67ef80-3b0b-11eb-80e9-744d37bf8a25.png)

![NoSQLBooster2](https://user-images.githubusercontent.com/41284486/101740134-cde5ca80-3b0b-11eb-9bec-97074d10766d.png)

**Comment by jhparkk** [comment]
db 버전은 4.4.1 입니다.

접속 정보는  mongodb://192.168.10.213:47017 -u root -p "sinsiway" --authenticationDatabase admin 
참고하시기 바랍니다

**Comment by sinsiway** [comment]
@jhparkk mongodb 버전이 올라감에 따라 java driver가 수용 못하던 문제가 있었습니다.
java driver 버전업 및 그에따른 영향도 처리 완료 하였습니다.
