### ISSUE TITLE
[연구소_박종한]mongodb 쿼리 실행 결과값 안보이는 현상

### ISSUE THREAD

**Issue by jhparkk** [sinsiway/data-studio-alpha#38]
쿼리 수행시 인식하지 못하는 쿼리도 있고 인식하는 쿼리도 있지만 에러가 떨어지고 결과 값이 보이지 않음
 
![NoSQLBooster_query1](https://user-images.githubusercontent.com/41284486/101741465-70527d80-3b0d-11eb-9e08-1c8190000701.png)
![datastudio_query1](https://user-images.githubusercontent.com/41284486/101741469-7183aa80-3b0d-11eb-8945-91e6f802f0f9.png)
![NoSQLBooster_query2](https://user-images.githubusercontent.com/41284486/101741471-7183aa80-3b0d-11eb-84e5-35bc188f1dbf.png)
![datastudio_query2](https://user-images.githubusercontent.com/41284486/101741473-721c4100-3b0d-11eb-906c-610d5675a7ab.png)
![NoSQLBooster_query3](https://user-images.githubusercontent.com/41284486/101741474-721c4100-3b0d-11eb-89ec-61d6fb00747d.png)
![datastudio_query3](https://user-images.githubusercontent.com/41284486/101741476-72b4d780-3b0d-11eb-9a6d-10fa011b98ce.png)

**Comment by jhparkk** [comment]
db 접속이 안됬는지도 모르겠음..

**Comment by sinsiway** [comment]
@jhparkk mongodb 버전이 올라감에 따라 java driver가 수용 못하던 문제가 있었습니다.
java driver 버전업 및 그에따른 영향도 처리 완료 하였습니다.

**Comment by sinsiwaysign** [comment]
몽고db 지원하는 버전이 따로 있나요?
