### ISSUE TITLE
[고객지원2팀_라정기] where 절 조건에 맞지 않는경우 레코드가 0 이어야 하는데 전에 조회한 값이 보임

### ISSUE THREAD

**Issue by licael** [sinsiway/data-studio-alpha#4]
where 절 조건에 맞지 않는 경우 레코드가 0 이어야 하는데 기존에 select 한 데이터로 리턴값이 보이게 됩니다.
데이터 조회시 오탐으로 판단할수 있을것 같습니다.

![select](https://user-images.githubusercontent.com/72367262/95034184-c82ecb80-06fb-11eb-80e2-3b53a2029dd2.gif)

**Comment by sinsiway** [comment]
@licael 개발자게에 이슈 전달되었습니다.

**Comment by sinsiway** [comment]
수정 완료

**Comment by sinsiway** [comment]
수정 완료

**Comment by poorants** [comment]
@licael 기능 개발 완료되어 패치에 적용되었습니다.
