### ISSUE TITLE
MySQL 오른쪽 네비게이션 바 SQL History

### ISSUE THREAD

**Issue by eunhae0617** [sinsiway/data-studio-alpha#44]
### **2.  SQL 히스토리 내용에서 수행 실패 한 sql문은 보여주지 않음**  

![DataStudio Favorties클릭](https://user-images.githubusercontent.com/68427371/103612809-929eb600-4f68-11eb-8d9c-55c48e2864d6.gif)

**Comment by sinsiway** [comment]
@eunhae0617 오류 수정 및 라벨 수정 완료하였습니다.
