### ISSUE TITLE
MySQL SQL script 결과- 실행계획, 메시지 

### ISSUE THREAD

**Issue by eunhae0617** [sinsiway/data-studio-alpha#45]
### **1. Execute Plan 으로 실행 하여도 아무런 작동이 없고, 실행계획 화면 자체가 열리지 않을 때도 있음**
![DataStudio Execute Plan](https://user-images.githubusercontent.com/68427371/103613892-c1b62700-4f6a-11eb-8c77-2c15f7a01eaa.gif)

### **2. 메시지가 너무 번잡하다. -> 성공실패는 화면 색으로, sql문과 오류 메시지를 간결하게 보여주기**
DBeaver 오류 메시지
![image](https://user-images.githubusercontent.com/68427371/103614036-0f329400-4f6b-11eb-8a36-dc841afde107.png)
QueryPie 성공 메시지 
![image](https://user-images.githubusercontent.com/68427371/103614173-56208980-4f6b-11eb-9a22-28bd9bd7332f.png)
QueryPie 실패 메시지 
![image](https://user-images.githubusercontent.com/68427371/103614221-6cc6e080-4f6b-11eb-978c-3ced5ceceaf1.png)

**Comment by sinsiway** [comment]
@eunhae0617 수정 완료
