### ISSUE TITLE
Oracle 오브젝트 뷰어 모션 오류 

### ISSUE THREAD

**Issue by eunhae0617** [sinsiway/data-studio-alpha#47]
###     **-> 아무런 모션을 취하지 않음
![DataStudio Oracle 오브젝트 모션](https://user-images.githubusercontent.com/68427371/103615001-22466380-4f6d-11eb-85b5-14947d20a58e.gif)

**Comment by sinsiway** [comment]
@eunhae0617 해당 db의 문자셋 오류로 정상 db 테스트 바람.
