### ISSUE TITLE
사용신청 문구 변경

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#48]
### **1. 사용 신청 > 모든 필수항목 입력 > '등록 완료' 클릭 시** 
![alert창_등록완료 후](https://user-images.githubusercontent.com/56990741/103733624-8597ca80-502d-11eb-89c9-7b9f8aaf0891.PNG)
토스트 메시지 문구 변경이 필요합니다.
기존 : 000(아이디) 사용자를 신청하였습니다. email 인증 및 관리자 승인 후 로그인 가능합니다.
변경 추천안 : 000(아이디)님, 로그인 하시고 고객님의 email로 보내드린 인증코드를 이용해 email 인증을 하시기 바랍니다.

사용자에게 로그인을 먼저 한 뒤에 email 인증을 하여야 한다는 문구를 남겨줄 필요가 있습니다.

### **2. 사용 신청 > 등록 완료 > 로그인 > E-MAIL 인증 >(관리자 승인 전) 재로그인 시** 
![이메일 인증 완료 후](https://user-images.githubusercontent.com/56990741/103735538-a104d480-5031-11eb-87c0-3d8426cb0ec9.PNG)
토스트 메시지 문구 변경이 필요합니다.
기존 : E-MAIL인증이 완료된 사용 신청 계정입니다. 관리자에게 승인 요청 바랍니다.
변경 추천안 : 관리자 승인을 기다리는 중입니다. 잠시만 기다려 주십시오.

사용자에게 관리자 승인까지 기다리기 바란다는 문구를 전달하는 것이 필요해보입니다.

**Comment by sinsiway** [comment]
@changwoo63 적용 완료
