### ISSUE TITLE
기능 추가 제안

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#49]
### **1. 사용 신청 > 등록 완료 > 로그인 > e-mail 발송 인증코드 기입 > '등록 완료' 클릭 시** 
![alert창_등록완료 후](https://user-images.githubusercontent.com/56990741/103733624-8597ca80-502d-11eb-89c9-7b9f8aaf0891.PNG)
사용자의 E-MAIL 인증이 완료되면 자동으로 관리자에게 사용 요청 메일을 발송하면 좋겠습니다.
이 기능을 제안하는 이유는
1. 자동 메일 발송을 통해 관리자의 빠른 승인이 가능합니다.
2. 사용 신청과 E-MAIL 인증을 하고, 또 관리자 승인 요청까지 3개의 일을 하는 것은 사용자가 불편해 할 수 있습니다.

### **2. 사용 신청 > 등록 완료 > 로그인 > E-MAIL 인증 > 관리자 승인 > 승인 완료 시** 
관리자 승인이 완료되면, 사용자에게 승인 완료 메일을 발송하면 좋겠습니다.
이 기능을 제안하는 이유는
1. 사용자가 승인 완료 사실을 빠르게 확인하여 데이터 스튜디오 서비스를 사용할 수 있습니다.
2. 관리자는 사용자에 대한 '승인 완료' 정보 전달을 자동화시킬 수 있습니다.

### **3. 사용 신청 내 E-MAIL 인증 기능 추가** 
![사람인](https://user-images.githubusercontent.com/56990741/103739014-5175d700-5038-11eb-8b89-8ced6560b19f.PNG)
![사람인2](https://user-images.githubusercontent.com/56990741/103739120-7ec28500-5038-11eb-9bbd-ab969b1a481d.PNG)
출처: https://www.saramin.co.kr/zf_user/member/registration/join
사용 신청 시 E-MAIL 인증 기능을 추가적으로 적용하여 UX를 개선하는 방법이 있습니다. 
이 기능을 제안하는 이유는
1. 기존의 사용 신청과 E-MAIL 인증 과정이 분할되어 있었는데 통합으로 진행하여 사용자의 편의를 증진시킬 수 있습니다. 

### **4. 로그인 페이지 SInsiway 로고 클릭시** 
![Sinsiway](https://user-images.githubusercontent.com/56990741/103739807-7b7bc900-5039-11eb-9b98-556203d4759d.PNG)
Sinsiway 로고 클릭시, 브라우저 새 탭을 열어 자사 홈페이지 링크로 이동하면 좋겠습니다.
이 기능을 제안하는 이유는
1. 사용자가 신시웨이 회사 정보와 기타 서비스를 파악하는 데에 홈페이지 링크가 필요할 거라 생각합니다.

### **5. SQL History, Job History 내에서 검색 시** 
![DBMS 검색](https://user-images.githubusercontent.com/56990741/103740472-9d298000-503a-11eb-95b8-3f918d20a8cc.PNG)
![SQL History 검색](https://user-images.githubusercontent.com/56990741/103740477-a0247080-503a-11eb-8273-e0d508c87536.PNG)
![카테고리별 검색](https://user-images.githubusercontent.com/56990741/103741420-5e94c500-503c-11eb-8e81-f74468aa3e30.PNG)
해당 페이지에서 검색 시, 카테고리 별 검색이 가능하면 좋겠습니다.
예를 들어, SQL History에서는 SQL 구문, DB명, 작성자 등으로 카테고리를 나눌 수 있습니다.
Job History에서는 문서제목, 문서내용 등으로 카테고리를 나눌 수 있습니다.
이 기능을 제안하는 이유는
1. 사용자가 원하는 검색을 효과적으로 할 수 있도록 돕기 위해서입니다.

### 6. 조직/사용자 목록에서 검색 시 자동완성 기능
![조직명 검색](https://user-images.githubusercontent.com/56990741/103741814-19bd5e00-503d-11eb-8e0b-0732e7a45018.gif)
![NAVER-Chrome-2021-01-06-16-40-12](https://user-images.githubusercontent.com/56990741/103742495-40c85f80-503e-11eb-9c92-09856f0344a9.gif)
출처: https://www.naver.com

입력창에서 한글 한 낱말이 형성되어야 관련 내용이 노출되고 있습니다. 자음만 입력했을 때는 관련 내용이 노출되지 않습니다.
자음을 입력하였을 때에 바로 관련 내용이 바로 노출되도록 하면 좋겠습니다.
일반 검색 사이트(Google, NAVER) 등에서 자음만 작성해도 자동완성 기능을 제공하고 있습니다. 
이 기능을 제안하는 이유는
1. 사용자가 빠르게 원하는 검색을 할 수 있도록 돕기 위해서입니다.

**Comment by sinsiway** [comment]
@changwoo63 1~3 제안사항을 고려하여 email 인증과 사용 신청 화면을 통합 하고, 사용자 신청이 완료 되면 관리자들에게 UI 화면에서 알림을 받을 수 있도록 개발 예정입니다.

4~5번 처리 완료하였습니다.
6번 팀내 협의 후 처리할 예정입니다.
