### ISSUE TITLE
[연구소_김동훈] 업데이트 내역 "다시 보지 않기" 동작하지 않는 현상.

### ISSUE THREAD

**Issue by poorants** [sinsiway/data-studio-alpha#5]
- 업데이트 내역 바에 "다시 보지 않기" 기능이 동작하지 않는 현상. 

![다신 보지않기 닫히지 않는 현상](https://user-images.githubusercontent.com/65228542/97124388-39015a80-1773-11eb-8f46-d7f67e9808e0.gif)

**Comment by sinsiway** [comment]
수정 완료
