### ISSUE TITLE
사용신청 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#50]
### **1. 사용 신청 > 사용자명 > 숫자 및 특수문자 입력 시** 
![사용자명_1](https://user-images.githubusercontent.com/56990741/103743407-70c43280-503f-11eb-9e90-ba2ff4d07a66.gif)
사용자명 란에 숫자 및 특수문자 입력 시, alert 문구가 노출되지 않습니다.

사용자명에 숫자와 특수문자 사용은 맞지 않기 때문에, '잘못된 입력입니다.' 또는 '잘못된 양식입니다.'라는 문구가 필요해 보입니다.

### **2. 사용 신청 > 신규 비밀번호 확인 > 미일치 입력 시** 
![비밀번호 확인_1](https://user-images.githubusercontent.com/56990741/103743825-1677a180-5040-11eb-81a2-46b5c58fe718.gif)
'비밀번호 확인' 입력란 하단에 '영문,숫자,특수문자를 혼합하여 입력해주세요.' 또는 '8~13자리 문자로 입력해 주십시오.' alert 문구를 노출시키지 않는 게 좋겠습니다.

비밀번호 확인은 비밀번호 입력값과 일치한지 확인하는 기능이기 때문에 위 alert 문구는 필요하지 않습니다.

**Comment by sinsiway** [comment]
@changwoo63 적용 완료
