### ISSUE TITLE
인증코드 메일 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#51]
### **인증코드 메일을 Gmail에서 확인 시** 
![gmail](https://user-images.githubusercontent.com/56990741/103744689-8a667980-5041-11eb-94b3-86faf1a186ac.PNG)
![naver mail](https://user-images.githubusercontent.com/56990741/103744700-8e929700-5041-11eb-8c8a-a8f4aa50e857.PNG)

인증 코드 메일 내용에 포함된 'Sinsiway' 로고 이미지가 gmail에서는 노출되지 않습니다.
사용자는 Sinsiway 로고 이미지가 있어야 메일 내용에 대한 신뢰감을 가질 수 있기 때문에 개선이 필요해 보입니다.

**Comment by sinsiway** [comment]
@changwoo63 gmail은 특성상 Google Image Proxy 라는 기능을 이용하여 보안상으로 1차적으로 걸러 보여줍니다.
여러가지 정책들로 인하여 이미지가 안보이는 상황이 발생 할 수 있습니다.
