### ISSUE TITLE
 페이지 상단 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#52]
### **페이지 상단 '남은 시간' 클릭 시**
![남은시간-링크연결 (2)](https://user-images.githubusercontent.com/56990741/103746753-f1396200-5044-11eb-9c7f-b3fa83231092.gif)

새 탭이 생기며 특정 링크로 연결됩니다.
이 기능은 특정 링크 연결이 필요하지 않기 때문에 연결을 제거하는 게 좋겠습니다.

**Comment by sinsiway** [comment]
@changwoo63 수정 완료
