### ISSUE TITLE
설정파트 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#53]
### **1. 설정 > 세션 > 세션 타임아웃 설정 - 미적용 현상**
![세션 타임아웃 미적용](https://user-images.githubusercontent.com/56990741/103747316-cd2a5080-5045-11eb-9335-920ea955a10d.gif)

세션 타임아웃을 400분으로 적용했음에도 기존 설정 시간(360분)으로 적용되고 있습니다. 

### **2. 설정 > 세션 > 에디터 > JDBC 드라이버 설정 > 삭제 > '아니오' 클릭 시 **
![세션 타임아웃 미적용](https://user-images.githubusercontent.com/56990741/103747316-cd2a5080-5045-11eb-9335-920ea955a10d.gif)

'아니오'를 누르면, 열려있는 설정 창이 닫혀집니다. 설정 창이 계속 유지되는 게 좋겠습니다.

**Comment by sinsiway** [comment]
@changwoo63  수정 완료
