### ISSUE TITLE
DBMS 관리 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#54]
### **DBMS 관리 > 새로고침 클릭 시 **
![DBMS 관리 새로고침](https://user-images.githubusercontent.com/56990741/103748053-e41d7280-5046-11eb-9c05-65b0c7cf813a.gif)

'새로고침 되었습니다.' 토스트 메시지가 필요해보입니다. 
실제로 실행되었는지 확인할 수 있는 가장 좋은 방법은 메시지 전달이기 때문입니다.

**Comment by sinsiway** [comment]
@changwoo63 수정 완료
