### ISSUE TITLE
DBMS 접근 관리 개선사항

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#55]
### **DBMS 접근 관리 > DBMS 목록 > 사용자 > 접근 변경 클릭 시 **
![DBMS 접근관리-접근 변경](https://user-images.githubusercontent.com/56990741/103749156-783c0980-5048-11eb-95c9-f9d2b807c81c.gif)

사용자/조직 목록의 내용이 서로 겹친 상태로 보이고 있습니다.

**Comment by sinsiway** [comment]
@changwoo63 수정 완료
