### ISSUE TITLE
에디터 접속 시간 소요

### ISSUE THREAD

**Issue by changwoo63** [sinsiway/data-studio-alpha#56]
### **DBMS 관리 > Redshift 접속 클릭 시 **
![Redshift 접속 시간소요](https://user-images.githubusercontent.com/56990741/103850845-aaeb0e00-50eb-11eb-9aa4-dab798a2c316.gif)
1. redshift-db 에디터 접속(탭 생성)까지 약 8초의 시간이 소요됩니다. 타 DB에 비해 접속 완료 시간이 오래 걸립니다.

**Comment by sinsiway** [comment]
@changwoo63 db 서버 마다 접속 시간 상이하게 다름.
