### ISSUE TITLE
[R&D_류대석] 조회 결과 없어도 가로 스크롤 제공 

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#58]
## 조회 결과 없음에도 가로 스크롤 제공 요청
조회 결과가 없어도 컬럼 확인을 위한 가로 스크롤이 제공 되었으면 합니다.
![image](https://user-images.githubusercontent.com/68979630/104673904-fb82ec80-5725-11eb-85ca-9a00b7e959de.png)

**Comment by sinsiway** [comment]
@sinsiwaysign 개선 완료 하였습니다.
