### ISSUE TITLE
[R&D_류대석] soha db auto script 500 error

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#59]
혹시 Soha db는 auto script 미지원인가요?
![image](https://user-images.githubusercontent.com/68979630/105163958-dfcd7b00-5b57-11eb-8a53-8a40f94d4a97.png)

**Comment by sinsiway** [comment]
@sinsiwaysign soha는 ddl만 제외하고 지원 가능하도록 수정 완료하였습니다.
