### ISSUE TITLE
[연구소_김동훈] 에디터 닫을 때 "auto commit" 옵션이지만 트랜젝션이 있다고 나오는 현상. 

### ISSUE THREAD

**Issue by poorants** [sinsiway/data-studio-alpha#6]
- "auto commit" 사용중인 세션을 닫을 때 트랜젝션이 있다고 팝업창이 나오는 현상. 

--- 

![트랜젝션 내용이 없는데 트랜잭션이 있다고 나오는 현상](https://user-images.githubusercontent.com/65228542/97124450-7fef5000-1773-11eb-9840-1bc76c57c30b.gif)

**Comment by sinsiway** [comment]
오류 수정 완료
