### ISSUE TITLE
[R&D_류대석] SQL Editor 임시 저장 기능의 비 일관성

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#61]
# SQL Editor 로그 아웃 시 쿼리 사라짐
- 환경: windows, chrome 87
타임 아웃 등으로 로그 아웃 된 후 재 로그인 시, 기존 접속한 세션의 에디터 창에 수행했던 SQL이 임시 저장 기능처럼 남아있게 되는데,
로그 아웃 버튼 클릭으로 로그 아웃 후 재 로그인 시 기존 접속 세션의 에디터가 초기화 됨
![image](https://user-images.githubusercontent.com/68979630/105449385-a7df4880-5cbb-11eb-90eb-daee63955752.png)

**Comment by sinsiway** [comment]
@sinsiwaysign 편집기 최근 작업 내용 저장 기준을 제일 마지막 수행했던 편집기 창의 sql text를 클라이언트 local 공간에 저장해 두도록 정리 및 개선 하였습니다.
