### ISSUE TITLE
[R&D_박종한]mongodb 쿼리 수행 정보 메시지 변경 요청

### ISSUE THREAD

**Issue by jhparkk** [sinsiway/data-studio-alpha#62]
![image](https://user-images.githubusercontent.com/41284486/105703171-2fdd8080-5f50-11eb-91b4-21e76afaaa8e.png)

해당 쿼리는 수행 되지 않음에도 불구하고 
수행여부는 "성공"
실행 결과는 not found db command를 내뱉고 있음

수행여부는 "실패"로 바꾸어야 할 듯..
그리고 결과에는 최근의 성공한 결과를 보여주는데, 쿼리가 실패한 상황에서도 그전에 조회한 결과가 유지 되어서
혼선의 여지가 있음.

**Comment by sinsiway** [comment]
@jhparkk 실패 처리 되도록 개선 완료
