### ISSUE TITLE
[R&D_류대석] 동일 컬럼명 조회 시 출력 오류

### ISSUE THREAD

**Issue by sinsiwaysign** [sinsiway/data-studio-alpha#67]
## 동일 컬럼명 데이터 출력 오류
- 환경:  windows 10, chrome 88, soha database

서로 다른 테이블을 조인하여 같은 명칭의 컬럼 조회 시 내용이 잘못 출력되는 현상
pact_inline_listener / pt_listen_addr 두 테이블 조인 후 listen_port 컬럼 조회 시
처음 출력되는 컬럼 값으로 두번째 컬럼 값이 덮어씌워지는 현상
![image](https://user-images.githubusercontent.com/68979630/107900226-be5b8580-6f83-11eb-878a-e1d588fce97f.png)

**Comment by sinsiway** [comment]
@sinsiwaysign 동일 컬럼일 경우 (숫자) 붙여서 data set 하도록 프로세스 추가하였습니다.
