### ISSUE TITLE
[연구소_김동훈] 검색 후 재검색이 되지 않는 현상. 

### ISSUE THREAD

**Issue by poorants** [sinsiway/data-studio-alpha#7]
- 검색 후 재검색이 되지 않는 현상. 

---

![검색 후 재검색이 안되는 현상](https://user-images.githubusercontent.com/65228542/97124879-3dc70e00-1775-11eb-9836-1db58bcbf0af.gif)

**Comment by sinsiway** [comment]
알고리즘 개선 완료
