### ISSUE TITLE
[연구소_김동훈] 롤백 시 DML 마크업 영역 색이 이상해지는 현상. 

### ISSUE THREAD

**Issue by poorants** [sinsiway/data-studio-alpha#9]
- CASE 01 다중 셀 업데이트 후 롤백.

![다중 셀 업데이트 롤백 시 마크업 영역이 이상한 현상](https://user-images.githubusercontent.com/65228542/97125083-0efd6780-1776-11eb-8059-d0542175fb59.gif)

---

- CASE 02 업데이트 영역 삭제 후 롤백.

![다중 셀 업데이트 롤백 시 마크업 영역이 이상한 현상-02](https://user-images.githubusercontent.com/65228542/97125096-1886cf80-1776-11eb-9d33-a31e316b9c80.gif)

**Comment by sinsiway** [comment]
두가지 케이스 수정 완료
